name: OneHand
description: Professionales a tu disposicion

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  
  flutter_svg: ^0.19.0
  http:
  adobe_xd: ^1.0.0+1
  cupertino_icons: ^1.0.0
  font_awesome_flutter:
  animated_text_kit: ^2.0.0
  modal_progress_hud: ^0.1.3
  firebase_auth: ^0.20.0+1
  firebase_database: ^6.0.0
  firebase_core: ^0.7.0
  curved_navigation_bar: ^0.3.7

    
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/



